server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: zipkin-sleuth
          uri: https://github.com/MelaniLav/tutorial-microservicios
          search-paths: config-data
  application:
    name: config-service
